(cl:in-package interbotix_xs_msgs-msg)
(cl:export '(BASE_X_CMD-VAL
          BASE_X_CMD
          BASE_THETA_CMD-VAL
          BASE_THETA_CMD
          BASE_RESET_ODOM_CMD-VAL
          BASE_RESET_ODOM_CMD
          PAN_CMD-VAL
          PAN_CMD
          TILT_CMD-VAL
          TILT_CMD
          EE_X_CMD-VAL
          EE_X_CMD
          EE_Y_CMD-VAL
          EE_Y_CMD
          EE_Z_CMD-VAL
          EE_Z_CMD
          EE_ROLL_CMD-VAL
          EE_ROLL_CMD
          EE_PITCH_CMD-VAL
          EE_PITCH_CMD
          WAIST_CMD-VAL
          WAIST_CMD
          GRIPPER_CMD-VAL
          GRIPPER_CMD
          POSE_CMD-VAL
          POSE_CMD
          SPEED_CMD-VAL
          SPEED_CMD
          SPEED_TOGGLE_CMD-VAL
          SPEED_TOGGLE_CMD
          GRIPPER_PWM_CMD-VAL
          GRIPPER_PWM_CMD
))