(cl:in-package interbotix_xs_msgs-msg)
(cl:export '(WORLD_X_CMD-VAL
          WORLD_X_CMD
          WORLD_Y_CMD-VAL
          WORLD_Y_CMD
          WORLD_YAW_CMD-VAL
          WORLD_YAW_CMD
          PLACE_X_CMD-VAL
          PLACE_X_CMD
          PLACE_Y_CMD-VAL
          PLACE_Y_CMD
          PLACE_Z_CMD-VAL
          PLACE_Z_CMD
          PLACE_ROLL_CMD-VAL
          PLACE_ROLL_CMD
          PLACE_PITCH_CMD-VAL
          PLACE_PITCH_CMD
          POSE_CMD-VAL
          POSE_CMD
          MOVE_TYPE_CMD-VAL
          MOVE_TYPE_CMD
          GAIT_TOGGLE_CMD-VAL
          GAIT_TOGGLE_CMD
          LEG_TOGGLE_CMD-VAL
          LEG_TOGGLE_CMD
          STANCE_CMD-VAL
          STANCE_CMD
          REBOOT_CMD-VAL
          REBOOT_CMD
          SET_HOME_POSE_CMD-VAL
          SET_HOME_POSE_CMD
          SPEED_CMD-VAL
          SPEED_CMD
          SPEED_TOGGLE_CMD-VAL
          SPEED_TOGGLE_CMD
))