// Generated by gencpp from file interbotix_xs_msgs/JointTrajectoryCommand.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_MSGS_MESSAGE_JOINTTRAJECTORYCOMMAND_H
#define INTERBOTIX_XS_MSGS_MESSAGE_JOINTTRAJECTORYCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace interbotix_xs_msgs
{
template <class ContainerAllocator>
struct JointTrajectoryCommand_
{
  typedef JointTrajectoryCommand_<ContainerAllocator> Type;

  JointTrajectoryCommand_()
    : cmd_type()
    , name()
    , traj()  {
    }
  JointTrajectoryCommand_(const ContainerAllocator& _alloc)
    : cmd_type(_alloc)
    , name(_alloc)
    , traj(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type_type;
  _cmd_type_type cmd_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _traj_type;
  _traj_type traj;





  typedef boost::shared_ptr< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JointTrajectoryCommand_

typedef ::interbotix_xs_msgs::JointTrajectoryCommand_<std::allocator<void> > JointTrajectoryCommand;

typedef boost::shared_ptr< ::interbotix_xs_msgs::JointTrajectoryCommand > JointTrajectoryCommandPtr;
typedef boost::shared_ptr< ::interbotix_xs_msgs::JointTrajectoryCommand const> JointTrajectoryCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator1> & lhs, const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_type == rhs.cmd_type &&
    lhs.name == rhs.name &&
    lhs.traj == rhs.traj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator1> & lhs, const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interbotix_xs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "039c1a8f9200d555267cf39243b5e969";
  }

  static const char* value(const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x039c1a8f9200d555ULL;
  static const uint64_t static_value2 = 0x267cf39243b5e969ULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_xs_msgs/JointTrajectoryCommand";
  }

  static const char* value(const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Command a joint trajectory to the desired joint(s). Note that the commands are processed differently based on the currently set operating mode.\n"
"# For example, if the operating mode is set to 'position', the commands are interpreted as positions in radians\n"
"\n"
"string cmd_type                               # set to 'single' for a single joint or 'group' for a group of joints\n"
"string name                                   # joint group name if 'cmd_type' is set to 'group' or joint name if 'cmd_type' is set to 'single'\n"
"trajectory_msgs/JointTrajectory traj          # ROS trajectory message\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_type);
      stream.next(m.name);
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTrajectoryCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interbotix_xs_msgs::JointTrajectoryCommand_<ContainerAllocator>& v)
  {
    s << indent << "cmd_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd_type);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_XS_MSGS_MESSAGE_JOINTTRAJECTORYCOMMAND_H
