// Generated by gencpp from file interbotix_xs_msgs/MotorGains.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_MSGS_MESSAGE_MOTORGAINS_H
#define INTERBOTIX_XS_MSGS_MESSAGE_MOTORGAINS_H

#include <ros/service_traits.h>


#include <interbotix_xs_msgs/MotorGainsRequest.h>
#include <interbotix_xs_msgs/MotorGainsResponse.h>


namespace interbotix_xs_msgs
{

struct MotorGains
{

typedef MotorGainsRequest Request;
typedef MotorGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorGains
} // namespace interbotix_xs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_msgs::MotorGains > {
  static const char* value()
  {
    return "7c362297bf8bae149936ba71305f3900";
  }

  static const char* value(const ::interbotix_xs_msgs::MotorGains&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_msgs::MotorGains > {
  static const char* value()
  {
    return "interbotix_xs_msgs/MotorGains";
  }

  static const char* value(const ::interbotix_xs_msgs::MotorGains&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_msgs::MotorGainsRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::MotorGains >
template<>
struct MD5Sum< ::interbotix_xs_msgs::MotorGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::MotorGains >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::MotorGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::MotorGainsRequest> should match
// service_traits::DataType< ::interbotix_xs_msgs::MotorGains >
template<>
struct DataType< ::interbotix_xs_msgs::MotorGainsRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::MotorGains >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::MotorGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_msgs::MotorGainsResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::MotorGains >
template<>
struct MD5Sum< ::interbotix_xs_msgs::MotorGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::MotorGains >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::MotorGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::MotorGainsResponse> should match
// service_traits::DataType< ::interbotix_xs_msgs::MotorGains >
template<>
struct DataType< ::interbotix_xs_msgs::MotorGainsResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::MotorGains >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::MotorGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_MSGS_MESSAGE_MOTORGAINS_H
