// Generated by gencpp from file interbotix_xs_msgs/RobotInfo.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_MSGS_MESSAGE_ROBOTINFO_H
#define INTERBOTIX_XS_MSGS_MESSAGE_ROBOTINFO_H

#include <ros/service_traits.h>


#include <interbotix_xs_msgs/RobotInfoRequest.h>
#include <interbotix_xs_msgs/RobotInfoResponse.h>


namespace interbotix_xs_msgs
{

struct RobotInfo
{

typedef RobotInfoRequest Request;
typedef RobotInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotInfo
} // namespace interbotix_xs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_msgs::RobotInfo > {
  static const char* value()
  {
    return "873f2223b25122251d4d3641d8411cf6";
  }

  static const char* value(const ::interbotix_xs_msgs::RobotInfo&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_msgs::RobotInfo > {
  static const char* value()
  {
    return "interbotix_xs_msgs/RobotInfo";
  }

  static const char* value(const ::interbotix_xs_msgs::RobotInfo&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_msgs::RobotInfoRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::RobotInfo >
template<>
struct MD5Sum< ::interbotix_xs_msgs::RobotInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::RobotInfoRequest> should match
// service_traits::DataType< ::interbotix_xs_msgs::RobotInfo >
template<>
struct DataType< ::interbotix_xs_msgs::RobotInfoRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_msgs::RobotInfoResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::RobotInfo >
template<>
struct MD5Sum< ::interbotix_xs_msgs::RobotInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::RobotInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::RobotInfoResponse> should match
// service_traits::DataType< ::interbotix_xs_msgs::RobotInfo >
template<>
struct DataType< ::interbotix_xs_msgs::RobotInfoResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::RobotInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_MSGS_MESSAGE_ROBOTINFO_H
