// Generated by gencpp from file interbotix_xs_msgs/TorqueEnable.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_MSGS_MESSAGE_TORQUEENABLE_H
#define INTERBOTIX_XS_MSGS_MESSAGE_TORQUEENABLE_H

#include <ros/service_traits.h>


#include <interbotix_xs_msgs/TorqueEnableRequest.h>
#include <interbotix_xs_msgs/TorqueEnableResponse.h>


namespace interbotix_xs_msgs
{

struct TorqueEnable
{

typedef TorqueEnableRequest Request;
typedef TorqueEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TorqueEnable
} // namespace interbotix_xs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_msgs::TorqueEnable > {
  static const char* value()
  {
    return "023452ade9f3d4979c75bd4e0d60f0c9";
  }

  static const char* value(const ::interbotix_xs_msgs::TorqueEnable&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_msgs::TorqueEnable > {
  static const char* value()
  {
    return "interbotix_xs_msgs/TorqueEnable";
  }

  static const char* value(const ::interbotix_xs_msgs::TorqueEnable&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_msgs::TorqueEnableRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::TorqueEnable >
template<>
struct MD5Sum< ::interbotix_xs_msgs::TorqueEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::TorqueEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::TorqueEnableRequest> should match
// service_traits::DataType< ::interbotix_xs_msgs::TorqueEnable >
template<>
struct DataType< ::interbotix_xs_msgs::TorqueEnableRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::TorqueEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_msgs::TorqueEnableResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_msgs::TorqueEnable >
template<>
struct MD5Sum< ::interbotix_xs_msgs::TorqueEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_msgs::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::TorqueEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_msgs::TorqueEnableResponse> should match
// service_traits::DataType< ::interbotix_xs_msgs::TorqueEnable >
template<>
struct DataType< ::interbotix_xs_msgs::TorqueEnableResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_msgs::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_msgs::TorqueEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_MSGS_MESSAGE_TORQUEENABLE_H
