// Generated by gencpp from file interbotix_xs_msgs/TurretJoy.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_MSGS_MESSAGE_TURRETJOY_H
#define INTERBOTIX_XS_MSGS_MESSAGE_TURRETJOY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interbotix_xs_msgs
{
template <class ContainerAllocator>
struct TurretJoy_
{
  typedef TurretJoy_<ContainerAllocator> Type;

  TurretJoy_()
    : pan_cmd(0)
    , tilt_cmd(0)
    , speed_cmd(0)
    , speed_toggle_cmd(0)  {
    }
  TurretJoy_(const ContainerAllocator& _alloc)
    : pan_cmd(0)
    , tilt_cmd(0)
    , speed_cmd(0)
    , speed_toggle_cmd(0)  {
  (void)_alloc;
    }



   typedef int8_t _pan_cmd_type;
  _pan_cmd_type pan_cmd;

   typedef int8_t _tilt_cmd_type;
  _tilt_cmd_type tilt_cmd;

   typedef int8_t _speed_cmd_type;
  _speed_cmd_type speed_cmd;

   typedef int8_t _speed_toggle_cmd_type;
  _speed_toggle_cmd_type speed_toggle_cmd;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PAN_CCW)
  #undef PAN_CCW
#endif
#if defined(_WIN32) && defined(PAN_CW)
  #undef PAN_CW
#endif
#if defined(_WIN32) && defined(TILT_UP)
  #undef TILT_UP
#endif
#if defined(_WIN32) && defined(TILT_DOWN)
  #undef TILT_DOWN
#endif
#if defined(_WIN32) && defined(PAN_TILT_HOME)
  #undef PAN_TILT_HOME
#endif
#if defined(_WIN32) && defined(SPEED_INC)
  #undef SPEED_INC
#endif
#if defined(_WIN32) && defined(SPEED_DEC)
  #undef SPEED_DEC
#endif
#if defined(_WIN32) && defined(SPEED_COURSE)
  #undef SPEED_COURSE
#endif
#if defined(_WIN32) && defined(SPEED_FINE)
  #undef SPEED_FINE
#endif

  enum {
    PAN_CCW = 1,
    PAN_CW = 2,
    TILT_UP = 3,
    TILT_DOWN = 4,
    PAN_TILT_HOME = 5,
    SPEED_INC = 6,
    SPEED_DEC = 7,
    SPEED_COURSE = 8,
    SPEED_FINE = 9,
  };


  typedef boost::shared_ptr< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> const> ConstPtr;

}; // struct TurretJoy_

typedef ::interbotix_xs_msgs::TurretJoy_<std::allocator<void> > TurretJoy;

typedef boost::shared_ptr< ::interbotix_xs_msgs::TurretJoy > TurretJoyPtr;
typedef boost::shared_ptr< ::interbotix_xs_msgs::TurretJoy const> TurretJoyConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator1> & lhs, const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator2> & rhs)
{
  return lhs.pan_cmd == rhs.pan_cmd &&
    lhs.tilt_cmd == rhs.tilt_cmd &&
    lhs.speed_cmd == rhs.speed_cmd &&
    lhs.speed_toggle_cmd == rhs.speed_toggle_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator1> & lhs, const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interbotix_xs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cac3aec45a4ead9e4b41e201bb45d797";
  }

  static const char* value(const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcac3aec45a4ead9eULL;
  static const uint64_t static_value2 = 0x4b41e201bb45d797ULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_xs_msgs/TurretJoy";
  }

  static const char* value(const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is used specifically in the interbotix_xsturret_simple_interface package\n"
"#\n"
"# Maps raw 'joy' commands to more specific ones to control an Interbotix turret\n"
"\n"
"# enum values that define the joystick controls for the robot\n"
"\n"
"#########################################################################################################\n"
"\n"
"# Control the pan-and-tilt mechanism\n"
"int8 PAN_CCW = 1\n"
"int8 PAN_CW = 2\n"
"int8 TILT_UP = 3\n"
"int8 TILT_DOWN = 4\n"
"int8 PAN_TILT_HOME = 5\n"
"\n"
"#########################################################################################################\n"
"\n"
"# Customize configurations for the Interbotix Turret\n"
"# Inc/Dec Joint speed\n"
"int8 SPEED_INC = 6\n"
"int8 SPEED_DEC = 7\n"
"\n"
"# Quickly toggle between a fast and slow speed setting\n"
"int8 SPEED_COURSE = 8\n"
"int8 SPEED_FINE = 9\n"
"\n"
"#########################################################################################################\n"
"\n"
"# Control the motion of the pan-and-tilt mechanism\n"
"int8 pan_cmd\n"
"int8 tilt_cmd\n"
"\n"
"# Speed Configs\n"
"int8 speed_cmd\n"
"int8 speed_toggle_cmd\n"
;
  }

  static const char* value(const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan_cmd);
      stream.next(m.tilt_cmd);
      stream.next(m.speed_cmd);
      stream.next(m.speed_toggle_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurretJoy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interbotix_xs_msgs::TurretJoy_<ContainerAllocator>& v)
  {
    s << indent << "pan_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pan_cmd);
    s << indent << "tilt_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.tilt_cmd);
    s << indent << "speed_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed_cmd);
    s << indent << "speed_toggle_cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed_toggle_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_XS_MSGS_MESSAGE_TURRETJOY_H
