// Generated by gencpp from file interbotix_perception_modules/ClusterInfoArray.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_PERCEPTION_MODULES_MESSAGE_CLUSTERINFOARRAY_H
#define INTERBOTIX_PERCEPTION_MODULES_MESSAGE_CLUSTERINFOARRAY_H

#include <ros/service_traits.h>


#include <interbotix_perception_modules/ClusterInfoArrayRequest.h>
#include <interbotix_perception_modules/ClusterInfoArrayResponse.h>


namespace interbotix_perception_modules
{

struct ClusterInfoArray
{

typedef ClusterInfoArrayRequest Request;
typedef ClusterInfoArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClusterInfoArray
} // namespace interbotix_perception_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_perception_modules::ClusterInfoArray > {
  static const char* value()
  {
    return "911bd211bd6fd7e568c4562cf40f28fd";
  }

  static const char* value(const ::interbotix_perception_modules::ClusterInfoArray&) { return value(); }
};

template<>
struct DataType< ::interbotix_perception_modules::ClusterInfoArray > {
  static const char* value()
  {
    return "interbotix_perception_modules/ClusterInfoArray";
  }

  static const char* value(const ::interbotix_perception_modules::ClusterInfoArray&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_perception_modules::ClusterInfoArrayRequest> should match
// service_traits::MD5Sum< ::interbotix_perception_modules::ClusterInfoArray >
template<>
struct MD5Sum< ::interbotix_perception_modules::ClusterInfoArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_perception_modules::ClusterInfoArray >::value();
  }
  static const char* value(const ::interbotix_perception_modules::ClusterInfoArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_perception_modules::ClusterInfoArrayRequest> should match
// service_traits::DataType< ::interbotix_perception_modules::ClusterInfoArray >
template<>
struct DataType< ::interbotix_perception_modules::ClusterInfoArrayRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_perception_modules::ClusterInfoArray >::value();
  }
  static const char* value(const ::interbotix_perception_modules::ClusterInfoArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_perception_modules::ClusterInfoArrayResponse> should match
// service_traits::MD5Sum< ::interbotix_perception_modules::ClusterInfoArray >
template<>
struct MD5Sum< ::interbotix_perception_modules::ClusterInfoArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_perception_modules::ClusterInfoArray >::value();
  }
  static const char* value(const ::interbotix_perception_modules::ClusterInfoArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_perception_modules::ClusterInfoArrayResponse> should match
// service_traits::DataType< ::interbotix_perception_modules::ClusterInfoArray >
template<>
struct DataType< ::interbotix_perception_modules::ClusterInfoArrayResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_perception_modules::ClusterInfoArray >::value();
  }
  static const char* value(const ::interbotix_perception_modules::ClusterInfoArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_PERCEPTION_MODULES_MESSAGE_CLUSTERINFOARRAY_H
