// Generated by gencpp from file interbotix_perception_modules/FilterParamsResponse.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMSRESPONSE_H
#define INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interbotix_perception_modules
{
template <class ContainerAllocator>
struct FilterParamsResponse_
{
  typedef FilterParamsResponse_<ContainerAllocator> Type;

  FilterParamsResponse_()
    {
    }
  FilterParamsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FilterParamsResponse_

typedef ::interbotix_perception_modules::FilterParamsResponse_<std::allocator<void> > FilterParamsResponse;

typedef boost::shared_ptr< ::interbotix_perception_modules::FilterParamsResponse > FilterParamsResponsePtr;
typedef boost::shared_ptr< ::interbotix_perception_modules::FilterParamsResponse const> FilterParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace interbotix_perception_modules

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_perception_modules/FilterParamsResponse";
  }

  static const char* value(const ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FilterParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::interbotix_perception_modules::FilterParamsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMSRESPONSE_H
