// Generated by gencpp from file interbotix_perception_modules/FilterParams.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMS_H
#define INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMS_H

#include <ros/service_traits.h>


#include <interbotix_perception_modules/FilterParamsRequest.h>
#include <interbotix_perception_modules/FilterParamsResponse.h>


namespace interbotix_perception_modules
{

struct FilterParams
{

typedef FilterParamsRequest Request;
typedef FilterParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FilterParams
} // namespace interbotix_perception_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_perception_modules::FilterParams > {
  static const char* value()
  {
    return "57d51b939efff834ad5e55a181a7a0a0";
  }

  static const char* value(const ::interbotix_perception_modules::FilterParams&) { return value(); }
};

template<>
struct DataType< ::interbotix_perception_modules::FilterParams > {
  static const char* value()
  {
    return "interbotix_perception_modules/FilterParams";
  }

  static const char* value(const ::interbotix_perception_modules::FilterParams&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_perception_modules::FilterParamsRequest> should match
// service_traits::MD5Sum< ::interbotix_perception_modules::FilterParams >
template<>
struct MD5Sum< ::interbotix_perception_modules::FilterParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_perception_modules::FilterParams >::value();
  }
  static const char* value(const ::interbotix_perception_modules::FilterParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_perception_modules::FilterParamsRequest> should match
// service_traits::DataType< ::interbotix_perception_modules::FilterParams >
template<>
struct DataType< ::interbotix_perception_modules::FilterParamsRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_perception_modules::FilterParams >::value();
  }
  static const char* value(const ::interbotix_perception_modules::FilterParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_perception_modules::FilterParamsResponse> should match
// service_traits::MD5Sum< ::interbotix_perception_modules::FilterParams >
template<>
struct MD5Sum< ::interbotix_perception_modules::FilterParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_perception_modules::FilterParams >::value();
  }
  static const char* value(const ::interbotix_perception_modules::FilterParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_perception_modules::FilterParamsResponse> should match
// service_traits::DataType< ::interbotix_perception_modules::FilterParams >
template<>
struct DataType< ::interbotix_perception_modules::FilterParamsResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_perception_modules::FilterParams >::value();
  }
  static const char* value(const ::interbotix_perception_modules::FilterParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_PERCEPTION_MODULES_MESSAGE_FILTERPARAMS_H
