(cl:defpackage interbotix_perception_modules-srv
  (:use )
  (:export
   "CLUSTERINFOARRAY"
   "<CLUSTERINFOARRAY-REQUEST>"
   "CLUSTERINFOARRAY-REQUEST"
   "<CLUSTERINFOARRAY-RESPONSE>"
   "CLUSTERINFOARRAY-RESPONSE"
   "FILTERPARAMS"
   "<FILTERPARAMS-REQUEST>"
   "FILTERPARAMS-REQUEST"
   "<FILTERPARAMS-RESPONSE>"
   "FILTERPARAMS-RESPONSE"
   "SNAPPICTURE"
   "<SNAPPICTURE-REQUEST>"
   "SNAPPICTURE-REQUEST"
   "<SNAPPICTURE-RESPONSE>"
   "SNAPPICTURE-RESPONSE"
  ))

