# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from interbotix_xs_msgs/LocobotJoy.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LocobotJoy(genpy.Message):
  _md5sum = "31ceb27301fc34085add57595354ba17"
  _type = "interbotix_xs_msgs/LocobotJoy"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message is used specifically in the interbotix_xslocobot_joy package
#
# Maps raw 'joy' commands to more specific ones to control an Interbotix LoCoBot

# enum values that define the joystick controls for the robot

#########################################################################################################

# Reset base odometry
int8 RESET_ODOM = 1

#########################################################################################################

# Control the pan-and-tilt mechanism
int8 PAN_CCW = 2
int8 PAN_CW = 3
int8 TILT_UP = 4
int8 TILT_DOWN = 5
int8 PAN_TILT_HOME = 6

#########################################################################################################

# Control the motion of the virtual 'ee_gripper_link' or end effector using the modern_robotics_ik engine
# Position Control
int8 EE_X_INC = 7
int8 EE_X_DEC = 8
int8 EE_Y_INC = 9
int8 EE_Y_DEC = 10
int8 EE_Z_INC = 11
int8 EE_Z_DEC = 12

# Orientation Control
int8 EE_ROLL_CCW = 13
int8 EE_ROLL_CW = 14
int8 EE_PITCH_UP = 15
int8 EE_PITCH_DOWN = 16

#########################################################################################################

# Control the motion of independent joints on the Arm or send predefined robot poses
# Waist Joint Control
int8 WAIST_CCW = 17
int8 WAIST_CW = 18

# Gripper Control
int8 GRIPPER_OPEN = 19
int8 GRIPPER_CLOSE = 20

# Pose Control
int8 HOME_POSE = 21
int8 SLEEP_POSE = 22

#########################################################################################################

# Customize configurations for the Interbotix Arm
# Inc/Dec Joint speed
int8 SPEED_INC = 23
int8 SPEED_DEC = 24

# Quickly toggle between a fast and slow speed setting
int8 SPEED_COURSE = 25
int8 SPEED_FINE = 26

# Inc/Dec Gripper pressure
int8 GRIPPER_PWM_INC = 27
int8 GRIPPER_PWM_DEC = 28

#########################################################################################################

# Control the motion of the Kobuki base
float64 base_x_cmd
float64 base_theta_cmd
int8 base_reset_odom_cmd

# Control the motion of the camera pan-and-tilt mechanism
int8 pan_cmd
int8 tilt_cmd

# Control the motion of the Interbotix Arm
int8 ee_x_cmd
int8 ee_y_cmd
int8 ee_z_cmd
int8 ee_roll_cmd
int8 ee_pitch_cmd

# Independent Joint/Pose Control
int8 waist_cmd
int8 gripper_cmd
int8 pose_cmd

# Arm Configs
int8 speed_cmd
int8 speed_toggle_cmd
int8 gripper_pwm_cmd
"""
  # Pseudo-constants
  RESET_ODOM = 1
  PAN_CCW = 2
  PAN_CW = 3
  TILT_UP = 4
  TILT_DOWN = 5
  PAN_TILT_HOME = 6
  EE_X_INC = 7
  EE_X_DEC = 8
  EE_Y_INC = 9
  EE_Y_DEC = 10
  EE_Z_INC = 11
  EE_Z_DEC = 12
  EE_ROLL_CCW = 13
  EE_ROLL_CW = 14
  EE_PITCH_UP = 15
  EE_PITCH_DOWN = 16
  WAIST_CCW = 17
  WAIST_CW = 18
  GRIPPER_OPEN = 19
  GRIPPER_CLOSE = 20
  HOME_POSE = 21
  SLEEP_POSE = 22
  SPEED_INC = 23
  SPEED_DEC = 24
  SPEED_COURSE = 25
  SPEED_FINE = 26
  GRIPPER_PWM_INC = 27
  GRIPPER_PWM_DEC = 28

  __slots__ = ['base_x_cmd','base_theta_cmd','base_reset_odom_cmd','pan_cmd','tilt_cmd','ee_x_cmd','ee_y_cmd','ee_z_cmd','ee_roll_cmd','ee_pitch_cmd','waist_cmd','gripper_cmd','pose_cmd','speed_cmd','speed_toggle_cmd','gripper_pwm_cmd']
  _slot_types = ['float64','float64','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_x_cmd,base_theta_cmd,base_reset_odom_cmd,pan_cmd,tilt_cmd,ee_x_cmd,ee_y_cmd,ee_z_cmd,ee_roll_cmd,ee_pitch_cmd,waist_cmd,gripper_cmd,pose_cmd,speed_cmd,speed_toggle_cmd,gripper_pwm_cmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocobotJoy, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.base_x_cmd is None:
        self.base_x_cmd = 0.
      if self.base_theta_cmd is None:
        self.base_theta_cmd = 0.
      if self.base_reset_odom_cmd is None:
        self.base_reset_odom_cmd = 0
      if self.pan_cmd is None:
        self.pan_cmd = 0
      if self.tilt_cmd is None:
        self.tilt_cmd = 0
      if self.ee_x_cmd is None:
        self.ee_x_cmd = 0
      if self.ee_y_cmd is None:
        self.ee_y_cmd = 0
      if self.ee_z_cmd is None:
        self.ee_z_cmd = 0
      if self.ee_roll_cmd is None:
        self.ee_roll_cmd = 0
      if self.ee_pitch_cmd is None:
        self.ee_pitch_cmd = 0
      if self.waist_cmd is None:
        self.waist_cmd = 0
      if self.gripper_cmd is None:
        self.gripper_cmd = 0
      if self.pose_cmd is None:
        self.pose_cmd = 0
      if self.speed_cmd is None:
        self.speed_cmd = 0
      if self.speed_toggle_cmd is None:
        self.speed_toggle_cmd = 0
      if self.gripper_pwm_cmd is None:
        self.gripper_pwm_cmd = 0
    else:
      self.base_x_cmd = 0.
      self.base_theta_cmd = 0.
      self.base_reset_odom_cmd = 0
      self.pan_cmd = 0
      self.tilt_cmd = 0
      self.ee_x_cmd = 0
      self.ee_y_cmd = 0
      self.ee_z_cmd = 0
      self.ee_roll_cmd = 0
      self.ee_pitch_cmd = 0
      self.waist_cmd = 0
      self.gripper_cmd = 0
      self.pose_cmd = 0
      self.speed_cmd = 0
      self.speed_toggle_cmd = 0
      self.gripper_pwm_cmd = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d14b().pack(_x.base_x_cmd, _x.base_theta_cmd, _x.base_reset_odom_cmd, _x.pan_cmd, _x.tilt_cmd, _x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.waist_cmd, _x.gripper_cmd, _x.pose_cmd, _x.speed_cmd, _x.speed_toggle_cmd, _x.gripper_pwm_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.base_x_cmd, _x.base_theta_cmd, _x.base_reset_odom_cmd, _x.pan_cmd, _x.tilt_cmd, _x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.waist_cmd, _x.gripper_cmd, _x.pose_cmd, _x.speed_cmd, _x.speed_toggle_cmd, _x.gripper_pwm_cmd,) = _get_struct_2d14b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d14b().pack(_x.base_x_cmd, _x.base_theta_cmd, _x.base_reset_odom_cmd, _x.pan_cmd, _x.tilt_cmd, _x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.waist_cmd, _x.gripper_cmd, _x.pose_cmd, _x.speed_cmd, _x.speed_toggle_cmd, _x.gripper_pwm_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.base_x_cmd, _x.base_theta_cmd, _x.base_reset_odom_cmd, _x.pan_cmd, _x.tilt_cmd, _x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.waist_cmd, _x.gripper_cmd, _x.pose_cmd, _x.speed_cmd, _x.speed_toggle_cmd, _x.gripper_pwm_cmd,) = _get_struct_2d14b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d14b = None
def _get_struct_2d14b():
    global _struct_2d14b
    if _struct_2d14b is None:
        _struct_2d14b = struct.Struct("<2d14b")
    return _struct_2d14b
