// Generated by gencpp from file interbotix_moveit_interface/MoveItPlan.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLAN_H
#define INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLAN_H

#include <ros/service_traits.h>


#include <interbotix_moveit_interface/MoveItPlanRequest.h>
#include <interbotix_moveit_interface/MoveItPlanResponse.h>


namespace interbotix_moveit_interface
{

struct MoveItPlan
{

typedef MoveItPlanRequest Request;
typedef MoveItPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveItPlan
} // namespace interbotix_moveit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_moveit_interface::MoveItPlan > {
  static const char* value()
  {
    return "eff4f39614e2625df73027e93071de20";
  }

  static const char* value(const ::interbotix_moveit_interface::MoveItPlan&) { return value(); }
};

template<>
struct DataType< ::interbotix_moveit_interface::MoveItPlan > {
  static const char* value()
  {
    return "interbotix_moveit_interface/MoveItPlan";
  }

  static const char* value(const ::interbotix_moveit_interface::MoveItPlan&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_moveit_interface::MoveItPlanRequest> should match
// service_traits::MD5Sum< ::interbotix_moveit_interface::MoveItPlan >
template<>
struct MD5Sum< ::interbotix_moveit_interface::MoveItPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_moveit_interface::MoveItPlan >::value();
  }
  static const char* value(const ::interbotix_moveit_interface::MoveItPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_moveit_interface::MoveItPlanRequest> should match
// service_traits::DataType< ::interbotix_moveit_interface::MoveItPlan >
template<>
struct DataType< ::interbotix_moveit_interface::MoveItPlanRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_moveit_interface::MoveItPlan >::value();
  }
  static const char* value(const ::interbotix_moveit_interface::MoveItPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_moveit_interface::MoveItPlanResponse> should match
// service_traits::MD5Sum< ::interbotix_moveit_interface::MoveItPlan >
template<>
struct MD5Sum< ::interbotix_moveit_interface::MoveItPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_moveit_interface::MoveItPlan >::value();
  }
  static const char* value(const ::interbotix_moveit_interface::MoveItPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_moveit_interface::MoveItPlanResponse> should match
// service_traits::DataType< ::interbotix_moveit_interface::MoveItPlan >
template<>
struct DataType< ::interbotix_moveit_interface::MoveItPlanResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_moveit_interface::MoveItPlan >::value();
  }
  static const char* value(const ::interbotix_moveit_interface::MoveItPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLAN_H
