// Generated by gencpp from file interbotix_moveit_interface/MoveItPlanResponse.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLANRESPONSE_H
#define INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace interbotix_moveit_interface
{
template <class ContainerAllocator>
struct MoveItPlanResponse_
{
  typedef MoveItPlanResponse_<ContainerAllocator> Type;

  MoveItPlanResponse_()
    : msg()
    , success(false)  {
    }
  MoveItPlanResponse_(const ContainerAllocator& _alloc)
    : msg(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _msg_type;
  _msg_type msg;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveItPlanResponse_

typedef ::interbotix_moveit_interface::MoveItPlanResponse_<std::allocator<void> > MoveItPlanResponse;

typedef boost::shared_ptr< ::interbotix_moveit_interface::MoveItPlanResponse > MoveItPlanResponsePtr;
typedef boost::shared_ptr< ::interbotix_moveit_interface::MoveItPlanResponse const> MoveItPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator1> & lhs, const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator1> & lhs, const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interbotix_moveit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6815ecbafa5176f5e638e681f8dd5385";
  }

  static const char* value(const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6815ecbafa5176f5ULL;
  static const uint64_t static_value2 = 0xe638e681f8dd5385ULL;
};

template<class ContainerAllocator>
struct DataType< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interbotix_moveit_interface/MoveItPlanResponse";
  }

  static const char* value(const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message if the planning or execution was successful; this is displayed in the custom GUI.\n"
"std_msgs/String msg\n"
"\n"
"# boolean to easily check if the planning or execution was successful.\n"
"bool success\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveItPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interbotix_moveit_interface::MoveItPlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.msg);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERBOTIX_MOVEIT_INTERFACE_MESSAGE_MOVEITPLANRESPONSE_H
