cluster_max_size: 1000
cluster_min_size: 138
cluster_tol: 0.02
plane_dist_thresh: 0.013000000000000001
plane_max_iter: 235
ror_min_neighbors: 5
ror_radius_search: 0.01
voxel_leaf_size: 0.005
x_filter_max: 0.25
x_filter_min: -0.15999999999999998
y_filter_max: 0.25
y_filter_min: -0.25
z_filter_max: 0.75
z_filter_min: 0.25
