cluster_max_size: 1000
cluster_min_size: 25
cluster_tol: 0.073
plane_dist_thresh: 0.008
plane_max_iter: 50
ror_min_neighbors: 5
ror_radius_search: 0.01
voxel_leaf_size: 0.004
x_filter_max: 0.20999999999999996
x_filter_min: -0.16999999999999998
y_filter_max: 0.25
y_filter_min: -0.26
z_filter_max: 0.66
z_filter_min: 0.2
